spring.application.name=mcpremoteclient

spring.ai.openai.apiKey=${OPENAI_API_KEY}
spring.ai.chat.client.enabled=false
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json

spring.ai.mcp.client.streamable-http.connections.remote.url=http://localhost:8090
spring.ai.mcp.client.streamable-http.connections.remote.endpoint=/mcp


spring.ai.mcp.client.request-timeout=60s