spring.application.name=openai
#spring.ai.openai.apiKey=${OPENAI_API_KEY}
#spring.ai.model.chat=ollama
#spring.ai.ollama.chat.model=llama3.2
spring.ai.openai.chat.model=ai/gemma3:1B-F16
spring.ai.openai.base-url=http://localhost:12434/engines/v1
spring.ai.openai.api-key=test