spring.application.name=mvc
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp
spring.mvc.view.resolve-on-forward=true
logging.level.org.springframework=debug
spring.datasource.url=jdbc:mysql://localhost:3306/test_app_db
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=root