spring.application.name=mvc
logging.level.org.springframework=info
spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=root


#spring.security.user.name=user
#spring.security.user.password=user

management.endpoints.web.exposure.include=*


#Below are the value just to verify relax binding concept of spring boot.
db.userName=root
db.user-password=root
db.server_port=3306
db.server-protocol=jdbc
db.TEST_FIELD=test

payment.stripe=true
#payment.paypall=false