spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://localhost:3306/test_app_db
    username: root
    password: root