services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    networks:
      - health-care
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
    volumes:
      - mysql_data:/var/lib/mysql

  doctor-service:
    build:
      context: ./doctor-service
    container_name: doctor-latest
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    ports:
      - '8081:8080'
    networks:
      - health-care
    depends_on:
      - mysqldb

  patient-service:
    build:
      context: ./patient-service
    container_name: patient-latest
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    ports:
      - '8082:8080'
    networks:
      - health-care
    depends_on:
      - mysqldb

networks:
  health-care:

volumes:
  mysql_data:
