spring.application.name=mcp

spring.ai.openai.apiKey=${OPENAI_API_KEY}
spring.ai.chat.client.enabled=false
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json

