spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: http://doctor-service:8080
          predicates:
            - Path=/api/v1/doctors/**
          filters:
            - GatewayAuthenticationFilter

        - id: patient-service
          uri: http://patient-service:8080
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - GatewayAuthenticationFilter

        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/api/v1/auth/**