version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - kafka-test

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - kafka-test

  producer-service:
    build:
      context: ./producer
    environment:
      BOOT_STRAP_SERVER: kafka:9092
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka-test

  consumer-service:
    build:
      context: ./consumer
    environment:
      BOOT_STRAP_SERVER: kafka:9092
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka-test

networks:
  kafka-test:
